# Use official Python image
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy requirements.txt first to leverage Docker cache
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . /app

# Expose port
EXPOSE 5000

# Use a non-root user to run the application
RUN adduser --disabled-password --gecos '' appuser
USER appuser

# Start Flask app
CMD ["python", "app.py"]
