apiVersion: v1
kind: Service
metadata:
  name: cew-network-service
  labels:
    app: cew-network
spec:
  selector:
    app: cew-network # Selects pods with the label app: cew-network
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 5000 # The port on the pod to forward traffic to
  type: LoadBalancer # Use LoadBalancer for cloud environments, NodePort for local testing, or ClusterIP for internal services